services:
  web:
    image: 207567788282.dkr.ecr.eu-west-2.amazonaws.com/flask-mysql:latest
    ports:
      - "5002:5002"  # Match your Flask app port!
    depends_on:
      - mydb

  mydb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
